### ISSUE TITLE
ABI e CAB

### ISSUE THREAD

**Issue by ChristianGiupponi** [deved-it/fattura-elettronica#10]
Ciao,  
nella sezione DatiPagamento manca la possibilità di indicare ABI e CAB

**Comment by salgua** [comment]
Ciao,
nella prossima release ci saranno i campi dinamici così sarà possibile aggiungere qualsiasi campo opzionale

**Comment by salgua** [comment]
Fatto. Anche questo stabile con la v1.1.0 che conto di rilasciare entro domani sera.
