### ISSUE TITLE
Problema Natura nella classe DatiCassaPrevidenziale

### ISSUE THREAD

**Issue by m4tt86** [deved-it/fattura-elettronica#109]
Buongiorno,
ho un problema con la classe DatiCassaPrevidenziale. Se imposto la natura così:

```php
$datiCassaPrevidenziale = new DatiCassaPrevidenziale(
        TipoCassa::INPS, 
        $aliquotaCassa, 
        $importoCassa, 
        $imponibile, 
        $aliquotaIVA, 
        null, 
        Natura::NonSoggetteAltro,
        null
    );
    $datiGenerali->setDatiCassaPrevidenziale($datiCassaPrevidenziale);

```

 Ricevo l'errore: 

```php
Error: Call to a member function toXmlBlock() on string in file /vendor/deved/fattura-elettronica/src/FatturaElettronica/FatturaElettronicaBody/DatiGenerali/DatiCassaPrevidenziale.php on line 89
```

Dove sto sbagliando? Il punto dove viene generato l'errore della classe in questione è qui: 

https://github.com/deved-it/fattura-elettronica/blob/478de73d31c027e8643f0ca1d9cde0d3f05b9d13/src/FatturaElettronica/FatturaElettronicaBody/DatiGenerali/DatiCassaPrevidenziale.php#L89C1-L89C39

**Comment by salgua** [comment]
è sicuramente un baco. Questa parte di codice non l'avevo scritta io, era stata aggiunta da Diego Truccolo. Nel blocco PHPDoc non sono stati specificati tutti i campi con i relativi tipi. Ad ogni modo tu gli stai passando la natura come stringa, quindi non è possibile poi chiamarci la funzione toXmlBlock(). Provo a correggere al volo.

**Comment by salgua** [comment]
Dovrei aver risolto
Ciao e grazie!
