### ISSUE TITLE
Controllo errato per il terzo intermediario in FatturaAdapter

### ISSUE THREAD

**Issue by pfalomo** [deved-it/fattura-elettronica#11]
https://github.com/deved-it/fattura-elettronica/blob/master/src/FatturaAdapter.php#L54 qui viene testata l'implementazione di `Deved\FatturaElettronica\FatturaInterface` ma in realtà bisogna testare `IntermediarioInterface::class`

**Comment by salgua** [comment]
Grazie @pfalomo, hai perfettamente ragione!

**Comment by salgua** [comment]
Pubblico a breve nella v1.1.0

**Comment by pfalomo** [comment]
Grande @salgua e grazie di aver creato questo pacchetto! Fatto davvero mooolto bene!

**Comment by pfalomo** [comment]
@salgua al momento uso la `v1.0.7`, ci sono particolari criticità nel fare l'upgrade?

**Comment by salgua** [comment]
@pfalomo non dovrebbero esserci, ogni release viene testata con phpunit facendo attenzione che il pregresso continui a funzionare :)
