### ISSUE TITLE
Creazione documentazione

### ISSUE THREAD

**Issue by salgua** [deved-it/fattura-elettronica#13]
@pfalomo ho creato un branch [documentation](https://github.com/deved-it/fattura-elettronica/tree/documentation), possiamo iniziare da qui!
Grazie!

**Comment by salgua** [comment]
Come ti dicevo il branch da usare è [gh-pages](https://github.com/deved-it/fattura-elettronica/tree/gh-pages)

**Comment by pfalomo** [comment]
Ottimo! Per esempio nel readme alla fine c'è scritto `FatturaElettronicaAdapter` ma il percorso giusto non è `\Deved\FatturaElettronica\FatturaAdapter`?

**Comment by salgua** [comment]
Certo! Grazie! [Sistemato](https://github.com/deved-it/fattura-elettronica/commit/c5def0bd405da59276d5a4ce34b896e8a5f6dd63)
