### ISSUE TITLE
Necessità di specificare l'iscrizione REA

### ISSUE THREAD

**Issue by AdamMadrzejewski** [deved-it/fattura-elettronica#20]
Nel file che rappresenta la struttura del file XML ([Tracciato Fattura](https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.pdf)) abbiamo l'elemento 1.2.4 <IscrizioneREA> che per se non è obbligatorio, ma leggendo la sua descrizione

> Blocco da valorizzare nei casi di società iscritte nel registro delle imprese ai sensi dell'art. 2250 del codice civile

Potremmo dedurre che nella maggior parte dei casi, questo campo deve essere specificato e quindi ritengo ci sia una certa urgenza nella sua implementazione. Solo i liberi professionisti e l’imprenditori agricoli che svolge attività essenziale non devono iscriversi al registro delle imprese e quindi non devono specificare quel campo.

Scrivo per avere da voi qualche informazione al riguardo, se mi sbaglio o se siete d'accordo. Per il momento questa mi risulta la migliore libreria PHP per la generazione del file XML per la fatturazione elettronica e potrei contribuire. Intanto attendo il vostro feedback.

**Comment by salgua** [comment]
@AdamMadrzejewski ho controllato ed hai perfettamente ragione! 
Provvedo al più presto e grazie per il tuo contributo!

**Comment by salgua** [comment]
Fatto
