### ISSUE TITLE
Adeguamento alla fatturazione differita

### ISSUE THREAD

**Issue by AdamMadrzejewski** [deved-it/fattura-elettronica#22]
Nel file che rappresenta la struttura del file XML ([Tracciato Fattura](https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.pdf)) abbiamo l'elemento 2.1.8 che per se non è obbligatorio, ma si riferisce alle specifiche per la fattura differita. Mi risulta che la libreria fa già tutto il necessario per la fattura immediata, ma se si riuscirebbe solo a specificare questo elemento cioè 2.1.8.1 (NumeroDDT) e 2.1.8.2 (DataDDT), allora andrebbe bene anche per la fatturazione differita.

L'elemento potrebbe prendere anche più righe, il caso che non ho mai avuto e non so quando si presenta nelle gestione aziendale. Comunque, potendo specificare solo questo elemento la libreria sarebbe anche in grado di gestire la fatturazione differita (cosa a me necessaria).

Non sono esperto di PHP, ma forse questa cosa si potrebbe specificare qui, come 5 elemento:

```
$datiGenerali = new DatiGenerali(
    TipoDocumento::Fattura,
    '2018-11-22',
    '2018221111',
    122
);
```

**Comment by salgua** [comment]
Grazie @AdamMadrzejewski, metto in coda lavori.

**Comment by salgua** [comment]
Fatto. A breve disponibile nella `v1.1.2`
