### ISSUE TITLE
Annotazione della data di effettuazione, quando diversa dalla emissione

### ISSUE THREAD

**Issue by AdamMadrzejewski** [deved-it/fattura-elettronica#23]
Implementando la fatturazione elettronica ho trovato dei testi che indicano la necessita di specificare la data dell'operazione/effettuazione, quando questa sia diversa dalla data di emissione della fattura. Credo che questo caso, in questi mesi, sarà abbastanza frequente, in quanto ci saranno sicuramente dei problemi con l'implementazione e generazione dei file xml. 

> "L’art. 11 del DL 119/2018, invece, modifica, a regime, inserendo la nuova lettera g-bis) dell’articolo 21 del D.P.R. 633/1972, i termini di emissione delle fatture (indipendentemente dal formato cartaceo o elettronico), stabilendo che, a partire dal 1° luglio 2019, la fattura potrà essere emessa entro 10 giorni dal momento di effettuazione dell’operazione (determinato ex art. 6 del DPR 633/72). **In tal caso, la data di effettuazione dovrà essere specificamente indicata sul documento, in quanto diversa da quella di emissione della fattura.**"

E anche questo: 

> Innanzi tutto, l’articolo 10 del dl 119/2018, prevede che **per i primi 6 mesi del 2019, non vengano applicate sanzioni in caso di emissione tardiva della fattura, purché questa venga inviata entro il termine di liquidazione dell’Iva del periodo**. La sanzione sarà invece ridotta dell’80% nel caso in cui la fattura emessa tardivamente rientri nella liquidazione periodica del mese o del trimestre successivo.
> 
> Inoltre, dal 1° luglio 2019, chi deve emettere fattura avrà 10 giorni di tempo dalla prestazione o dalla vendita, novità che va ad applicarsi a tutte le fatture e non solo a quelle elettroniche. In tal caso, **sarà comunque necessario indicare in fattura che questa non è stata emessa contestualmente all’effettuazione dell’operazione**.  

Nel file che rappresenta la struttura del file XML ([Tracciato Fattura](https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.pdf)) non riesco a trovare un elemento che potrebbe servire a specificare questo caso.

Cosa ne pensate? Una volta individuato il campo si potrà provvedere alla sua implementazione, ma prima dobbiamo capire se è necessario e come si fa :)

**Comment by Bibendus83** [comment]
Credo si parli dei campi DataInizioPeriodo e DataFinePeriodo, c'è solo da capire se il termine dei 10 giorni vale dalla data di inizio o da quella di fine.

**Comment by Bibendus83** [comment]
Con un aggiornamento di ottobre hanno fatto passare queste modifiche
http://www.gazzettaufficiale.it/eli/id/2018/10/23/18G00151/sg

Leggendo l'articolo 11 si desume che dal primo luglio scatterà l'obbligo di fatturare entro 10 giorni dall'erogazione della prestazione.
Per erogazione della prestazione si intende il momento in cui viene effettuato un pagamento, anche parziale.
Non credo quindi ci siano campi da compilare nell'xml, presumo ci saranno sanzioni se verrà rilevato un incasso antecedente di 10 giorni alla data di emissione della fattura.

**Comment by salgua** [comment]
@Bibendus83 sì d'accordo, ma abbiamo fatto un po' di confusione. Tu hai fatto riferimento ai campi `DataInizioPeriodo` e `DataFinePeriodo` che sono obbligatori se la fattura si riferisce ad un arco temporale (es. operatore telefonico che emette fattura per un determinato bimestre). L'obbligo di indicare il periodo esisteva anche prima, ma era sufficiente indicarlo in modo descrittivo nella riga fattura. Adesso è obbligatorio indicarlo negli appositi campi. Sull'obbligo di emettere la fattura entro un determinato periodo, es. 10 giorni dalla ricezione del pagamento, hai ragione tu, non serve intervenire nell'xml, ma sono due cose distinte.

**Comment by Bibendus83** [comment]
Ah ok, non capivo a cosa servissero quei campi.
Comunque il chiarimento sulla legge è saltato fuori chiedendo sul forum italia.

**Comment by salgua** [comment]
Confermo che è possibile specificare il periodo di riferimento di ogni riga in questo modo:

    $riga->DataInizioPeriodo = '2018-05-01';
    $riga->DataFinePeriodo = '2018-05-31';
