### ISSUE TITLE
Compatibilità con PHP 7

### ISSUE THREAD

**Issue by bergheil** [deved-it/fattura-elettronica#24]
Buonasera, ho provato ad installare la libreria su una debian 8.7 con PHP 7 ma sembra ci sia un problema di compatibilità della libreria ext-xmlwriter. Nel mio server ho la versione 7.0.33 mentre è richiesta la 7.1 minimo.
Forse bisogna avere una versione superiore di PHP? io ho la 7.0.33.

Grazie

**Comment by salgua** [comment]
Ciao! Perdonami ma c'era un refuso nel file composer.json. Prova ora. Grazie!

**Comment by bergheil** [comment]
Grazie e buon anno




<https://www.scrum.org/Assessments>

Di Perna Francesco
francesco.diperna@gmail.com

Scrum Master & Developer
www.francescodiperna.eu

  <https://www.facebook.com/francesco.diperna.14> [image: LinkedIn]
<https://www.linkedin.com/in/diperna>v[image: Scrum Master & Developer]
<https://www.scrum.org/Assessments>[image: Scrum Master & Developer]
<https://www.scrum.org/Assessments>


“Se noi ombre vi siamo dispiaciuti, immaginate come se veduti ci aveste in
sogno, e come una visione di fantasia la nostra apparizione.” W.S.

Pensa all'ambiente e non stampare questa e-mail se non strettamente
necessario" Ai sensi del Decreto Legislativo n. 196/2003, si precisa che le
informazioni contenute in questo messaggio e negli eventuali allegati sono
riservate e per uso esclusivo del destinatario. Persone diverse dallo
stesso non possono copiare o distribuire il messaggio a terzi. Chiunque
riceva questo messaggio per errore, Ã¨ pregato di distruggerlo e di
informare immediatamente francesco.diperna@gmail.com




Il giorno mer 2 gen 2019 alle ore 19:09 salgua <notifications@github.com>
ha scritto:
