### ISSUE TITLE
DatiPagamento opzionale

### ISSUE THREAD

**Issue by slipperyfrank** [deved-it/fattura-elettronica#26]
FatturaElettronicaFactory->create() richiede un oggetto DatiPagamento.
Dalle [specifiche tecniche](https://www.fatturapa.gov.it/export/fatturazione/sdi/Specifiche_tecniche_del_formato_FatturaPA_v1.2.1.pdf), il blocco DatiPagamento non è opzionale?

Si potrebbe aggiungere un metodo setDatiPagamento anziché passare i dati direttamente al metodo create.

**Comment by salgua** [comment]
Grazie @slipperyfrank, 
anche il [costruttore di FatturaElettronicaBody](https://github.com/deved-it/fattura-elettronica/blob/c0af094cf17159c9c297789e625482b6a41c7924/src/FatturaElettronica/FatturaElettronicaBody.php#L38) erroneamente lo richiede in modo obbligatorio.
Provvedo subito a sistemare entrambi i file.

**Comment by salgua** [comment]
Fatto. Se non vuoi inserire i DatiPagamento passa `null` all'attributo `$datiPagamento` di `FatturaElettronicaFactory->create()`

**Comment by slipperyfrank** [comment]
Non è possibile passare valore `null` all'attributo `$datiPagamento`, perché sia il metodo `FatturaElettronicaFactory->create()` che `FatturaElettronicaBody->__construct` richiedono esplicitamente una istanza di `DatiPagamento`.
Si potrebbe pensare di togliere il parametro `$datiPagamento`  in `FatturaElettronicaFactory->create()` e aggiungere un metodo `SetDatiPagamento`

**Comment by salgua** [comment]
Ciao!
Non mi risulta, forse non stai utilizzando l'ultima release. 
[Guarda qui](https://github.com/deved-it/fattura-elettronica/blob/4c1e888c1c4ff77daec1efb915089457c9c46c79/src/FatturaElettronicaFactory.php#L154)
e [guarda qui](https://github.com/deved-it/fattura-elettronica/blob/4c1e888c1c4ff77daec1efb915089457c9c46c79/src/FatturaElettronica/FatturaElettronicaBody.php#L38)

ti consiglio un `composer update` se ha installato la libreria con composer, o un `git pull` se l'hai clonata.

Grazie!
