### ISSUE TITLE
campo "Causale" in DatiGenerali

### ISSUE THREAD

**Issue by bergheil** [deved-it/fattura-elettronica#28]
Ciao, nei Dati Generali bisogna aggiungere il campo Causale. 
Ho già fatto la modifica sul progetto clonato.
Saluti

**Comment by salgua** [comment]
Non necessario. Basta usare la proprietà dinamica:

    $datiGenerali = new DatiGenerali(
            TipoDocumento::Fattura,
            '2018-11-22',
            '2018221111',
            122
    );
    $datiGenerali->Causale = "Fattura di prova";

**Comment by pfalomo** [comment]
@salgua  ![image](https://user-images.githubusercontent.com/44964509/50827553-0e94a200-133f-11e9-8903-e94b839c01ab.png) nell'esempio che fa l'AdE sembra che ci sia un limite di 200 caratteri e che la causale vada quindi splittata in più pezzi.

Lo gestiamo?

**Comment by salgua** [comment]
Ciao Paolo, ok, metto in coda lavori!
