### ISSUE TITLE
DatiContratto da impementare

### ISSUE THREAD

**Issue by bergheil** [deved-it/fattura-elettronica#30]
Buongiorno, nel file DatiGenerali.php leggo un TODO:

//todo: implementare DatiOrdineAcquisto, DatiContratto etc. (facoltativi)

Dovrei generare la parte "DatiContratto".
Avete intenzione di implementarla a breve?

Grazie

**Comment by salgua** [comment]
buongiorno @bergheil 
se ti serve cerco di implementarla il prima possibile. Metto in coda lavori. 
Grazie!

**Comment by bergheil** [comment]
Si Grazie

**Comment by salgua** [comment]
Fatto. A breve rendo disponibile in `v1.1.3`
