### ISSUE TITLE
Nel caso di fattura estera se manca il codice fiscale inserisce lo stesso il tag [CodiceFiscale] 

### ISSUE THREAD

**Issue by diegottt** [deved-it/fattura-elettronica#31]
**Describe the bug**

**To Reproduce**
Describe the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by diegottt** [comment]
Ho modificato DatiAnagrafici.php nella funzione toXmlBlock in questo modo:
if ($this->codiceFiscale) {
            $writer->writeElement('CodiceFiscale', $this->codiceFiscale);
        }

**Comment by diegottt** [comment]
La validazione dell'agenzia delle entrate da' errore senza questa modifica.

**Comment by salgua** [comment]
Fatto. A breve rilascio `v1.1.3` con fix.
