### ISSUE TITLE
Dovrei implementare l'importazione dell'XML, oltre al canale SDIFTP, avete già qualcosa? O se vi interessa ve lo rendo disponibile appena finito.

### ISSUE THREAD

**Issue by diegottt** [deved-it/fattura-elettronica#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by salgua** [comment]
Ciao! Per adesso la libreria non si preoccupa di dialogare con l'SDI. Ho visto che il Team Developers Italia se ne dovrebbe occupare [qui](https://github.com/italia/fatturapa-testsdi) o [qui](https://github.com/italia/fatturapa-php-sdk), ma non so a che punto siano...

**Comment by diegottt** [comment]
si ho visto qualcosa anche se il canale ftp non mi sembra implementato se non per la semplice copia dei file...in ogni caso prenderò spunto...mentre per il parsing dell'xml pensavo di utilizzare i vostri oggetti implementando un metodo di lettura e assegnazione delle variabili in modo da avere tutto uniformato nella stessa struttura dati. In secondo luogo credo che creerò un metodo di dialogo con il mio framework andando ad implementare un metodo nella classe che uso come interfaccia. Se può interessarvi ve lo giro, se avete un'idea diversa fatemi sapere, se non vi interessa non c'è problema..volevo solo restituire il favore che mi avete fatto implementando questa esportazione. grazie, ciao

**Comment by salgua** [comment]
@diegottt grazie a te per la collaborazione! Puoi rendere il tuo codice opensource creando un nuovo progetto o facendo un fork di questo. Se ci sono modifiche che possono essere direttamente unite a questo repository puoi fare una pull request che valuterò molto volentieri.
Grazie ancora e a presto!
