### ISSUE TITLE
Data in DatiContratto

### ISSUE THREAD

**Issue by bergheil** [deved-it/fattura-elettronica#36]
Prima di tutto vi ringrazio per l'aggiunta dei Dati del Contratto.
Volevo chiedervi se è possibile aggiungere anche il campo "Data" (che manca), come di seguito:

 <DatiContratto>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>596441</IdDocumento>
        <Data>2018-07-20</Data>
        <NumItem>1</NumItem>
</DatiContratto>

**Comment by salgua** [comment]
@bergheil il campo Data non è obbligatorio pertanto non l'ho aggiunto nel costruttore. Puoi comunque aggiungerlo dinamicamente utilizzando la proprietà dinamica. Un esempio

    $datiContratto = new DatiGenerali\DatiContratto('123', [1, 2]);
    $datiContratto->Data = '2018-12-01';
    $datiContratto->CodiceCIG = 'ABCDEF';
    $datiContratto->addDatiContratto(new DatiGenerali\DatiContratto('234', [3,4]));
    $datiContratto->addDatiContratto(new DatiGenerali\DatiContratto('567'));

devo trovare il tempo per completare la documentazione 😄
