### ISSUE TITLE
Aggiungere possibilità di specificare Nome e Cognome in dati anagrafici

### ISSUE THREAD

**Issue by salgua** [deved-it/fattura-elettronica#38]
Aggiungere possibilità di specificare Nome e Cognome in dati anagrafici in alternativa a denominazione se persona fisica

**Comment by AdamMadrzejewski** [comment]
Credo la condizione dovrebbe essere racchiusa in questo modo:

```
if ($this->denominazione) {
    $writer->writeElement('Denominazione', $this->denominazione);
} else {
    $this->writeXmlField('Nome', $writer);
    $this->writeXmlField('Cognome', $writer);
}
```

Per evitare errori che sono specificati tutti due. Intendo i codici 00200 nel [Tracciato fattura](https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.pdf) nella colonna "Codice e descrizione dell'errore in caso di controllo non superato"

1) "è valorizzato ma lo sono pure i campi <Nome> e/o <Cognome> seguenti)"
2) "è valorizzato ma lo è pure il campo <Denominazione> precedente"

**Comment by salgua** [comment]
La tua osservazione sarebbe corretta, ma con le proprietà dinamiche è possibile comunque aggiungere qualsiasi tag, senza controllo da parte della libreria. Posso aggiungere qualsiasi elemento, ad esempio in questo modo:

`$blocco->ProprietaXYZ` = 'valore 123';

nel caso del Nome e Cognome ho dovuto usare il metodo `writeXmlField` perché avevo la necessità che l'output avvenisse proprio in quel punto, altrimenti, come per altri tag, non ci sarebbe stato bisogno di modificare la classe. Detto questo, posso applicare la modifica da te proposta, ma resta comunque di responsabilità di chi utilizza la libreria sapere quali tag sta utilizzando, in che combinazione e sequenza, nel rispetto dello schema xsd, altrimenti i controlli da aggiungere sarebbero veramente tanti.
