### ISSUE TITLE
Dettaglio pagamenti multipli

### ISSUE THREAD

**Issue by bergheil** [deved-it/fattura-elettronica#39]
Buongiorno, nel caso ci siano più scadenze di pagamento è possibile indicarle?
Dalla struttura del progetto mi sembra di intuire che sia possibile identificare un solo dettaglio di pagamento, corretto?

Grazie

**Comment by salgua** [comment]
@bergheil hai ragione, al momento è possibile specificare un solo blocco DatiPagamento. Lo modifico e lo rendo ripetibile. Grazie.

**Comment by salgua** [comment]
Fatto. Per aggiungere blocchi multipli:

    $datiPagamento = new DatiPagamento(
            ModalitaPagamento::Contanti,
            '2018-11-30',
            60,
            null,
            null,
            'TP01'
    );
    $datiPagamento->ABI = '12345';
    $datiPagamento->CAB = '56789';
    $datiPagamento->addBlock(new DatiPagamento(
          ModalitaPagamento::Contanti,
          '2018-12-31',
          62,
          null,
          null,
          'TP01'
    ));

**Comment by bergheil** [comment]
Ho provato ma ottengo il seguente errore:

*array* *(size=5)*
      0 => int 2048
      1 => string 'Deved\FatturaElettronica\XmlBlock and
Deved\FatturaElettronica\Traits\MagicFieldsTrait define the same
property ($xmlFields) in the composition of
Deved\FatturaElettronica\FatturaElettronica\FatturaElettronicaBody\DatiPagamento.
This might be incompatible, to improve maintainability consider using
accessor methods in traits instead. Class was composed' *(length=353)*
      2 => string
'C:\Progetti\NetBeansProjects\EniFatture\vendor\deved\fattura-elettronica\src\FatturaElettronica\FatturaElettronicaBody\DatiPagamento.php'
*(length=136)*
      3 => int 80
      4 =>
        *array* *(size=1)*
          'file' => string
'C:\Progetti\NetBeansProjects\EniFatture\vendor\composer/../deved/fattura-elettronica/src\FatturaElettronica\FatturaElettronicaBody\DatiPagamento.php'
*(length=148)*
  1 =>


Grazie


<https://www.scrum.org/Assessments>

Di Perna Francesco
francesco.diperna@gmail.com

Scrum Master & Developer
www.francescodiperna.eu

  <https://www.facebook.com/francesco.diperna.14> [image: LinkedIn]
<https://www.linkedin.com/in/diperna>v[image: Scrum Master & Developer]
<https://www.scrum.org/Assessments>[image: Scrum Master & Developer]
<https://www.scrum.org/Assessments>


“Se noi ombre vi siamo dispiaciuti, immaginate come se veduti ci aveste in
sogno, e come una visione di fantasia la nostra apparizione.” W.S.

Pensa all'ambiente e non stampare questa e-mail se non strettamente
necessario" Ai sensi del Decreto Legislativo n. 196/2003, si precisa che le
informazioni contenute in questo messaggio e negli eventuali allegati sono
riservate e per uso esclusivo del destinatario. Persone diverse dallo
stesso non possono copiare o distribuire il messaggio a terzi. Chiunque
riceva questo messaggio per errore, Ã¨ pregato di distruggerlo e di
informare immediatamente francesco.diperna@gmail.com




Il giorno mer 9 gen 2019 alle ore 16:41 salgua <notifications@github.com>
ha scritto:
