### ISSUE TITLE
Fattura Impresa individuale

### ISSUE THREAD

**Issue by francescolovecchio** [deved-it/fattura-elettronica#4]
**Is your feature request related to a problem? Please describe.**
Ciao, per l'impresa individuale, nel campo IdTrasmittente/IdCodice deve esserci il c.f. e non la p. iva

**Describe the solution you'd like**
Bisognerebbe indicare il tipo di impresa in modo che inserisca il c.f. piuttosto che la p.iva

**Describe alternatives you've considered**
Sto terminando la verifica degli altri campi prima di verificare le possibili soluzioni

**Comment by salgua** [comment]
@francescolovecchio grazie mille per il tuo contributo. Faccio le verifiche del caso e cerco di sistemare al più presto.

**Comment by salgua** [comment]
@francescolovecchio dovrei aver [risolto](https://github.com/deved-it/fattura-elettronica/commit/911bf6d6b680c32146277c9aacc58a051f3bf169). Il problema riguardava la creazione di fatture utilizzando la classe FatturaElettronicaFactory, usavo la partita iva al posto del codice fiscale. Il problema non si poneva per le società che hanno PIVA = CF. 
Grazie ancora!

**Comment by francescolovecchio** [comment]
Grazie! Purtroppo era poco chiara la documentazione in quanto il tracciato dice Partita IVA mentre le specifiche tecniche dicono Codice Fiscale.

Grazie a te! Se avessi conosciuto meglio le società avrei proposto io la modifica ma purtroppo avevo solo questa evidenza :)
