### ISSUE TITLE
Aggiungere possibilità di specificare ID Trasmittente

### ISSUE THREAD

**Issue by rupert978** [deved-it/fattura-elettronica#41]
Le informazioni di IdTrasmittente potrebbero non combaciare con idpaese e codicefiscale del cedente/prestatore.
Utilizzando la classe FatturaElettronicaFactory il metodo setCedentePrestatore crea un'istanza della classe idTrasmittente sempre con le informazioni di cui sopra e non è possibile assegnare altri valori alla proprietà idTrasmittente in quanto protected.
Credo possa bastare aggiungere un semplice metodo alla classe FatturaElettronicaFactory come per esempio setIscrizioneRea.
Se può essere utile ho già la modifica pronta da proporre con una Pull request.
Saluti
Roberto

**Comment by salgua** [comment]
Grazie!
