### ISSUE TITLE
E' possibile aggiungere la ritenuta e il contributo enasarco ecc..?

### ISSUE THREAD

**Issue by diegottt** [deved-it/fattura-elettronica#43]
Sto scrivendo il codice per gestirlo, non ho ben capito come inviarvi il codice scritto

**Comment by salgua** [comment]
Ciao, basta fare una pull request. Mi raccomando, rispettare le [PHP Standard Recommendations](https://www.php-fig.org/psr/), in modo particolare PSR-1 e PSR-2. Grazie!

**Comment by diegottt** [comment]
Per gli standard copio esattamente il vostro codice....ma per il pull request come faccio? Io lavoro da linea di comando direttamente da Linux....scusate l'ignoranza

Il 25 gennaio 2019 09:02:13 CET, salgua <notifications@github.com> ha scritto:
>Ciao, basta fare una pull request. Mi raccomando, rispettare le [PHP
>Standard Recommendations](https://www.php-fig.org/psr/), in modo
>particolare PSR-1 e PSR-2. Grazie!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deved-it/fattura-elettronica/issues/43#issuecomment-457488083

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by salgua** [comment]
- Fai un fork del progetto cliccando sul pulsante in alto a dx
- Cloni il repository ottenuto dal fork (lo trovi nel tuo profilo)
- Applichi le modifiche in locale
- Fai il push delle modifiche sul tuo repository
- Dal tuo repository, crei una pull request (da interfaccia web)

**Comment by salgua** [comment]
Fatto. Grazie!
