### ISSUE TITLE
Errore quando si inseriscono i dati di pagamento senza una data

### ISSUE THREAD

**Issue by bergheil** [deved-it/fattura-elettronica#44]
Buonasera,

quando creo i dati di pagamento nel seguente modo:

$datiPagamento = new DatiPagamento(
            ModalitaPagamento::RIDUtenze,
            '',
           100
        );

senza indicare una data di scadenza del pagamento, in fase di generazione dell'xml ottengo l'errore seguente:

array (size=5)
      0 => int 2048
      1 => string 'Deved\FatturaElettronica\XmlBlock and Deved\FatturaElettronica\Traits\MagicFieldsTrait define the same property ($xmlFields) in the composition of Deved\FatturaElettronica\FatturaElettronica\FatturaElettronicaBody\DatiPagamento. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed' (length=353)
      2 => string '....\vendor\deved\fattura-elettronica\src\FatturaElettronica\FatturaElettronicaBody\DatiPagamento.php' (length=136)
      3 => int 80
      4 => 
        array (size=1)
          'file' => string '....\vendor\composer/../deved/fattura-elettronica/src\FatturaElettronica\FatturaElettronicaBody\DatiPagamento.php' (length=148)

Grazie

**Comment by salgua** [comment]
Risolto nell'ultima [pull request](https://github.com/deved-it/fattura-elettronica/pull/46)
