### ISSUE TITLE
Problema con generazione importo totale fattura

### ISSUE THREAD

**Issue by ChristianGiupponi** [deved-it/fattura-elettronica#5]
Ciao,  
ho implementato il tuo package ma verificando l'XML generato con l'XSD ufficiale che puoi trovare qui: 

https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/Schema_del_file_xml_FatturaPA_versione_1.2.xsd

Alla voce `Amount2DecimalType` viene dichiarato un controllo con questo pattern:

`<xs:pattern value="[\-]?[0-9]{1,11}\.[0-9]{2}" />`

e non contempla la virgola per le migliaia mentre nel package usi `number_format($this->importoTotaleDocumento, 2)` che la aggiunge per default.

Sarebbe necessario modificarlo in modo da rendere compatibile la generazione per fatture oltre le migliaia.
Se vuoi ti posso mandare io una PR

**Comment by xfudox** [comment]
Ho avuto lo stesso problema ma non trovavo la causa, pensavo fosse qualcosa di più complesso.

Aspetto la correzione allora.

**Comment by salgua** [comment]
@ChristianGiupponi Grazie per la segnalazione! Sistemo subito

**Comment by ChristianGiupponi** [comment]
Grazie @salgua, ho notato che il problema è su tutti i campi di importo, anche PrezzoUnitario etc

**Comment by salgua** [comment]
eh sì... purtroppo hai notato bene! Mi è sfuggito che number_format aggiunge la "," come separatore di migliaia. Adesso applico il fix dappertutto.

**Comment by ChristianGiupponi** [comment]
se può velocizzarti il lavoro, questi sono i file dove appare `number_format`:

```
fattura-elettronica/src/FatturaElettronica/FatturaElettronicaBody/DatiBeniServizi/Linea.php:
fattura-elettronica/src/FatturaElettronica/FatturaElettronicaBody/DatiBeniServizi/DatiRiepilogo.php:    
fattura-elettronica/src/FatturaElettronica/FatturaElettronicaBody/DatiPagamento.php:
fattura-elettronica/src/FatturaElettronica/FatturaElettronicaBody/DatiGenerali.php:
```

**Comment by salgua** [comment]
[Problema risolto qui](https://github.com/deved-it/fattura-elettronica/commit/45ed798401935c65cb5273f9bfb438cd4961984d)! Grazie ancora
