### ISSUE TITLE
Dati di pagamento senza scadenza

### ISSUE THREAD

**Issue by bergheil** [deved-it/fattura-elettronica#50]
Salve, nell'esempio riportato nella documentazione i dati di pagamento possono essere definiti nel modo seguente:

$datiPagamento = new DatiPagamento(
    ModalitaPagamento::SEPA_CORE,
    '2018-11-30',
    122
);

Ma come faccio a non indicare la data di scadenza? Io vorrei indicare solo la modalità di pagamento ed il totale, senza indicare la data di scadenza. Al momento non è possibile poichè se non valorizzo il secondo parametro mi crea un XML non conforme allo standard definito dall'agenzia delle entrate.

Grazie

**Comment by salgua** [comment]
Ciao @bergheil,
hai ragione, [ho risolto qui](https://github.com/deved-it/fattura-elettronica/commit/a2a5f44b79904fd534c3db6493a1bd5b136e0402)
usa pure la dev-master.
Grazie,
Salvatore

**Comment by salgua** [comment]
non ho rilasciato la relase stabile, dammi un minuto che lo faccio ora

**Comment by salgua** [comment]
fatto. Rilasciata la `v1.1.9` , fai pure un `composer update` e poi va bene il codice che hai indicato.
Ciao e grazie,
Salvatore

**Comment by bergheil** [comment]
Grazie




<https://www.scrum.org/Assessments>

Di Perna Francesco
francesco.diperna@gmail.com

Scrum Master & Developer
www.francescodiperna.eu

  <https://www.facebook.com/francesco.diperna.14> [image: LinkedIn]
<https://www.linkedin.com/in/diperna>v[image: Scrum Master & Developer]
<https://www.scrum.org/Assessments>[image: Scrum Master & Developer]
<https://www.scrum.org/Assessments>


“Se noi ombre vi siamo dispiaciuti, immaginate come se veduti ci aveste in
sogno, e come una visione di fantasia la nostra apparizione.” W.S.

Pensa all'ambiente e non stampare questa e-mail se non strettamente
necessario" Ai sensi del Decreto Legislativo n. 196/2003, si precisa che le
informazioni contenute in questo messaggio e negli eventuali allegati sono
riservate e per uso esclusivo del destinatario. Persone diverse dallo
stesso non possono copiare o distribuire il messaggio a terzi. Chiunque
riceva questo messaggio per errore, Ã¨ pregato di distruggerlo e di
informare immediatamente francesco.diperna@gmail.com




<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 4 feb 2019 alle ore 10:36 salgua <notifications@github.com>
ha scritto:
