### ISSUE TITLE
Come impostare il nome ed il cognome del cessionario committente?

### ISSUE THREAD

**Issue by shinesoftware** [deved-it/fattura-elettronica#55]
**Describe the bug**
Vorrei impostare il nome del cessionario committente ma non riesco a capire come usare la classe DatiAnagrafici

**Additional context**
Grazie mille per il tuo lavoro!!!

**Comment by salgua** [comment]
Ciao,
basta non indicare la denominazione nel costruttore e poi usare le proprietà magiche per `nome` e `cognome`:

    $cessionario = new DatiAnagrafici('XYZYZX77M04H888K');
    $cessionario->Nome = 'Pinco';
    $cessionario->Cognome = 'Pallino';
    
Grazie a te,
Salvatore
