### ISSUE TITLE
ref. Dati di Riepilogo ed Imposta

### ISSUE THREAD

**Issue by shinesoftware** [deved-it/fattura-elettronica#58]
**Describe the bug**
Il codice calcola un imposta partendo da una costante applicata nel codice sorgente ed impostata a 22. Il problema nasce quando un esercente deve realizzare una fattura con più aliquote ed in questo caso il modulo deve generare diverse sezioni relative ai DatiRiepilogo. Vedi https://forum.italia.it/t/aliquote-multiple-in-una-fattura-elettronica/5369/3 

**To Reproduce**
Vedi file alla riga 64 - [FatturaElettronica/FatturaElettronicaBody/DatiBeniServizi.php](https://github.com/deved-it/fattura-elettronica/blob/master/src/FatturaElettronica/FatturaElettronicaBody/DatiBeniServizi.php#L64)

**Expected behavior**
E' necessario lasciare la possibilità di impostare un'aliquota corretta o di disabilitare la sezione dei dati di riepilogo.

Grazie

**Comment by salgua** [comment]
Si tratta di una vecchia parte di codice, sicuramente da rimuovere o sistemare. Inizialmente non erano stati presi in considerazione casi con aliquota IVA diversi da 22 e veniva in  automatico calcolato un unico blocco di riepilogo. Come puoi vedere il calcolo automatico avviene solo se non gli passi tu un oggetto `DatiRiepilogo`, pertanto quello che devi fare è crearti il blocco (che è ripetibile, ovvero può includere più blocchi DatiRiepilogo) e passarlo al costruttore di DatiBeniServizi.

**Comment by shinesoftware** [comment]
Potresti farmi un piccolo esempio di una chiamata con due aliquote differenti ed una senza imposta?

grazie

**Comment by salgua** [comment]
Quando crei la prima istanza di `DatiRiepilogo` devi passargli i dati del primo blocco. Poi con `addDatiRiepilogo($datiRiepilogo2)` aggiungi i blocchi successivi

**Comment by salgua** [comment]
Trovi l'esempio [qui](https://github.com/deved-it/fattura-elettronica/blob/1f0d0551c53296b4165a71b687f5f0800813f30a/tests/FatturaAliquoteMultipleTest.php#L175)
