### ISSUE TITLE
Impostazione intermediario

### ISSUE THREAD

**Issue by ChristianGiupponi** [deved-it/fattura-elettronica#6]
Ciao,
dopo l'ultimo update `1.0.6` con l'introduzione dell'intermediario, usando il codice di esempio del readme ottengo questo errore:

`Type error: Argument 1 passed to Deved\FatturaElettronica\FatturaElettronicaFactory::setIntermediario() must be an instance of Deved\FatturaElettronica\FatturaElettronica\FatturaElettronicaHeader\Common\DatiAnagrafici, null given,`

sembra che sia obbligatorio ma seguendo le specifice del fiel XSD risulta opzionale:

https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/Schema_del_file_xml_FatturaPA_versione_1.2.xsd

```<xs:element name="TerzoIntermediarioOSoggettoEmittente" type="TerzoIntermediarioSoggettoEmittenteType" minOccurs="0" />```

**Comment by salgua** [comment]
Controllo subito

**Comment by salgua** [comment]
Dovrei aver risolto nella v1.0.7, appena rilasciata. Appena puoi se provi e mi dai conferma chiudo l'issue.

**Comment by ChristianGiupponi** [comment]
Sembra risolto!

**Comment by salgua** [comment]
Perfetto! Grazie ancora!
