### ISSUE TITLE
Fattura con linee con diverse aliquote

### ISSUE THREAD

**Issue by francesco-giacobazzi-italcube** [deved-it/fattura-elettronica#7]
**Is your feature request related to a problem? Please describe.**
Al momento non è possibile inserire in fattura linee con aliquote differenti.

**Describe the solution you'd like**
Avere la possibilità di inserire linee con aliquote differenti.

**Comment by salgua** [comment]
@francesco-giacobazzi-italcube hai ragione, al momento non è possibile farlo. 
[Metto in cantiere per una prossima release](https://github.com/deved-it/fattura-elettronica/milestone/4), dammi qualche giorno.
Intanto grazie

**Comment by salgua** [comment]
Rilasciato nella `v1.1.0`
