### ISSUE TITLE
Supporto schema 1.6?

### ISSUE THREAD

**Issue by mircobabini** [deved-it/fattura-elettronica#74]
Il repo è abbandonato oppure è previsto un aggiornamento?

**Comment by salgua** [comment]
è previsto un aggiornamento

**Comment by vittominacori** [comment]
è prevista una data per il rilascio o comunque c'è un fork/PR dove è possibile visionare le modifiche?

la normativa partirà dal 1 gennaio.

**Comment by vittominacori** [comment]
@salgua da gennaio i nuovi codici sono obbligatori, c'è una PR pending per i codici Natura.

Non vedo commit ne branch da mesi, il progetto si è fermato?
