### ISSUE TITLE
Installazione

### ISSUE THREAD

**Issue by sroselli** [deved-it/fattura-elettronica#75]
Buonasera, chiedo solo come posso fare per installare il tutto su DB ospitato su spazio web altervista e testare l'applicativo in PHP.
Ho intanto inviato il ZIP allo spazio web ed attendo chiarimenti

Grazie

**Comment by salgua** [comment]
si tratta di una libreria da installare con composer  
https://getcomposer.org/doc/00-intro.md  
la libreria va integrata con un applicativo esistente attraverso le sue interfacce
