### ISSUE TITLE
Gestione della natura dell'iva dove richiesto

### ISSUE THREAD

**Issue by francesco-giacobazzi-italcube** [deved-it/fattura-elettronica#8]
**Is your feature request related to a problem? Please describe.**
Per alcuni tipi di iva bisogna gestirne la natura.

**Describe the solution you'd like**
Bisogna poter passare i codici della natura per i tipi di iva che lo richiedono, io lo aggiungerei nella definizione della linea, così oltre a passare l'iva, se necessario si passa anche il codice della natura.

**Additional context**
Codici natura iva:
N1		escluse ex art. 15											
N2		non soggette											
N3		non imponibili											
N4		esenti											
N5		regime del margine / IVA non esposta in fattura											
N6		inversione contabile (per le operazioni in reverse charge ovvero nei casi di autofatturazione per acquisti extra UE di servizi ovvero per importazioni di beni nei soli casi previsti)											
N7		IVA assolta in altro stato UE (vendite a distanza ex art. 40 c. 3 e 4 e art. 41 c. 1 lett. b,  DL 331/93; prestazione di servizi di telecomunicazioni, tele-radiodiffusione ed elettronici ex art. 7-sexies lett. f, g, art. 74-sexies DPR 633/72)

**Comment by salgua** [comment]
Ok per tutto! Tieni solo presente che il codice della natura è obbligatorio  solo se l’operazione non rientra tre le operazioni fiscalmente “imponibili” o nei casi di inversione contabile, quindi quando l'aliquota IVA è uguale a 0. Negli altri casi di aliquote IVA (22, 10 etc.) non bisogna passare la natura.

**Comment by salgua** [comment]
Rilasciato nella `v1.1.0`

**Comment by mircobabini** [comment]
@salgua recupero questo argomento che, seppur antico, risulta attuale.

Lavorando con CGN, in caso di Servizi resi a committenti UE (escluso iva art.7-ter, il famoso passato dalla natura N6 alla natura N2.1) non è sufficiente inserire la natura nei DatiRiepilogo, è altresì necessario inserirla nella singola Linea.

**Errore di CGN in caso di Natura completamente non inserita:** La fattura presenta degli errori : Natura non presente a fronte di Aliquota IVA pari a 0

**Errore di CGN in caso di Natura inserita solo in riepilogo ordine:** La fattura presenta degli errori : Natura non presente a fronte di Aliquota IVA pari a 0,Tutti i valori di natura dell’operazione presenti nelle linee di dettaglio di una fattura o nei dati di cassa previdenziale devono essere presenti anche nei dati di riepilogo

La soluzione è appunto aggiungere la Natura anche nella singola Linea.
Credo sarebbe corretto aggiungere i dovuti getter/setters in `DatiRiepilogo` e `Linea`.

Ad oggi:
```
<?php
$datiRiepilogo = new DatiRiepilogo( 100, 0 );
if ( ! $isCustomerItalian ) {
	$datiRiepilogo->Natura               = Natura::NonSoggetteArt7;
	$datiRiepilogo->RiferimentoNormativo = 'Escluso art.7-ter - Servizi resi a committenti UE';
}
```

Mentre, per le linee:
```
$row = new Linea(
        $line_name,
        $line_item->item_total,
        $line_code,
        $line_item->quantity,
        'NR',
        $line_item->tax_percentage,
        'Codice articolo'
);

if ( ! $isCustomerItalian ) {
	$row->Natura = Natura::NonSoggetteArt7;
}
```
