### ISSUE TITLE
Supporto a Titolo e CodEORI

### ISSUE THREAD

**Issue by danielebuso** [deved-it/fattura-elettronica#84]
Nei `DatiAnagrafici` per un `TerzoIntermediarioOSoggettoEmittente` mancano le seguenti due proprietà

- `<Titolo>` Titolo onorifico del terzo intermediario
- `<CodEORI>` Codice EORI del terzo intermediario

**Comment by salgua** [comment]
dovresti già poter aggiungere Titolo e CodEORI senza ulteriori modifiche usando i "magic fields", senza necessità di aggiungerli al costruttore

    $datiAnagrafici = new DatiAnagrafici('XYZYZX77M04H888K', 'Pinco Palla');
    $datiAnagrafici->CodEORI = "xxxxx";
    $datAnagrafici->Titolo = "yyyy";

fammi pure sapere se ti funziona.

Ciao e grazie,
Salvatore

**Comment by danielebuso** [comment]
Grazie per il riscontro, sfortunatamente i due campi vanno messi dentro il tag `Anagrafica` e non nel tag principale `DatiAnagrafici` quindi non è fattibile direttamente con i magic fields.
