### ISSUE TITLE
DatiBeniServizi - Unità di misura obbligatoria

### ISSUE THREAD

**Issue by ChristianGiupponi** [deved-it/fattura-elettronica#9]
Ciao,  
nella parte di creazione delle linee `DatiBeniServizi` c'è di default la scritta `pz` come Unità di Misura ma alcune volte è suprerfluo, non sarebbe meglio lasciare quel campo nullo e inserirlo in fattura solo se presente?

**Comment by salgua** [comment]
Ciao Christian, 
l'unità di misura diventa obbligatoria se si specifica la quantità, per questo motivo il default per la quantità è 1 mentre per l'unità di misura è 'pz'. Potrei mettere "null" su entrambi. 
Ad ogni modo nelle prossime release permetterò di aggiungere qualsiasi campo dinamicamente usando le proprietà magiche di php, quindi una volta istanziata una classe potrai aggiungere campi così

```
$blocco->campoA
$blocco->campoB
$blocco->campoC 
```

**Comment by salgua** [comment]
Fatto. Rilascio stabile nella v1.1.0
